### ISSUE TITLE
Option to show x easy payments with Laybuy on product price area.

### ISSUE THREAD

**Issue by LiamKarlMitchell** [Laybuy/Magento-2#4]
Hi is it possible to put something like this on each product page when the Lay Buy payment method is available?

![image](https://user-images.githubusercontent.com/1968109/41325581-323a7948-6f0f-11e8-8a46-94149fe5d401.png)

Such as that the number of weekly payments and $.. could be a configured value.
The $ would be the cost of item / number of payments.

Thinking is this could help guide users towards a preferred payment method.

Do you have any advice on how to go about adding this kind of thing to this extension?

Edit: Actually I am working on this now found an example for putting blocks into catalog_product_view.

**Comment by LiamKarlMitchell** [comment]
Ended up going with this.
![image](https://user-images.githubusercontent.com/1968109/41330598-9088a182-6f28-11e8-8a68-7ecfad810100.png)

I'll file a pull request.

**Comment by nikolai-overdose** [comment]
Hi @LiamKarlMitchell - just confirming we can now close this issue?

Cheers

**Comment by LiamKarlMitchell** [comment]
Sure, It's in the Pull Request.
